Repository kubernetes-sigs/slack-infra, pull requests merged in 2021-02, with the labels that each got.

#42 slack: fix error check
  slack/slack.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#41 slack/bot: add moderate words bot
  .gitignore
  cluster/ingress.yaml
  cluster/slack-moderator-words/deployment.yaml
  cluster/slack-moderator-words/service.yaml
  go.mod
  go.sum
  slack-moderate-words/.gcloudignore
  slack-moderate-words/.gitignore
  slack-moderate-words/Dockerfile
  slack-moderate-words/README.md
  slack-moderate-words/events.go
  slack-moderate-words/events_test.go
  slack-moderate-words/filters.yaml
  slack-moderate-words/healthz.go
  slack-moderate-words/healthz_test.go
  slack-moderate-words/main.go
  slack-moderate-words/model/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#43 slack-moderator-words: update configs and add to variants.yaml
  README.md
  cluster/slack-moderator-words/deployment.yaml
  cluster/slack-moderator-words/filters.yaml
  cluster/slack-moderator-words/service.yaml
  slack-moderate-words/Dockerfile
  slack-moderator-words/.gcloudignore
  slack-moderator-words/.gitignore
  slack-moderator-words/Dockerfile
  slack-moderator-words/README.md
  slack-moderator-words/events.go
  slack-moderator-words/events_test.go
  slack-moderator-words/filters.yaml
  slack-moderator-words/healthz.go
  slack-moderator-words/healthz_test.go
  slack-moderator-words/main.go
  slack-moderator-words/model/types.go
  variants.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M
