Repository kubernetes-sigs/slack-infra, pull requests merged in 2021-04, with the labels that each got.

#49 slack-moderator-words: dont try to join a channel that is already member and add some rate limit retry
  slack-moderator-words/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#51 owners: add spiffxp and nikhita as approvers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#44 Update slack-infra image registries
  cluster/slack-event-log/deployment.yaml
  cluster/slack-moderator-words/deployment.yaml
  cluster/slack-moderator/deployment.yaml
  cluster/slack-post-message/deployment.yaml
  cluster/slack-welcomer/deployment.yaml
  cluster/slackin/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
